---

- name: "Install docker apt key"
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present

- name: "Install docker apt repository"
  apt_repository: repo="deb https://get.docker.com/ubuntu docker main" state=present

- name: "Install docker package"
  apt: name=lxc-docker state=present

- name: "Install python docker package"
  pip: name=docker-py

- name: "Configure docker host"
  lineinfile: >
    dest=/etc/default/docker
    state=present
    regexp='^#?DOCKER_OPTS='
    line='DOCKER_OPTS="-H unix:///var/run/docker.sock -H tcp://0.0.0.0:4243"'
  notify: restart docker

- name: "Installing docker-enter"
  shell: "docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter"
  args:
    creates: /usr/local/bin/docker-enter
